eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8770
spring:
  application:
    name: turbine-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
turbine:
  aggregator:
    cluster-config: default
  app-config: user-service
  cluster-name-expression: new String("default")
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS